# Generated by Django 5.1.6 on 2025-02-09 08:03

import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_type', models.CharField(choices=[('individual', 'Jismoniy shaxs'), ('legal_entity', 'Yuridik shaxs')], default='individual', max_length=20)),
                ('full_name', models.CharField(max_length=255, verbose_name='F.I.SH.')),
                ('phone_number', models.CharField(max_length=20, validators=[main.models.validate_uzb_phone], verbose_name='Telefon raqam')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('pending', 'Moderatsiyada'), ('confirmed', 'Tasdiqlangan'), ('rejected', 'Bekor qilingan')], default='new', max_length=20, verbose_name='Holati')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Homiylik summasi')),
                ('payment_method', models.CharField(choices=[('transfer', 'Pul o‘tkazmalari'), ('cash', 'Naqd pul'), ('card', 'Plastik karta')], max_length=32, verbose_name='To‘lov turi')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tashkilot nomi')),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255, verbose_name='F.I.Sh.')),
                ('phone_number', models.CharField(max_length=20, validators=[main.models.validate_uzb_phone], verbose_name='Telefon raqam')),
                ('degree_type', models.CharField(choices=[('Bakalavr', 'Bakalavr'), ('Magistr', 'Magistr')], max_length=10, verbose_name='Talabalik turi')),
                ('contract_amount', models.PositiveIntegerField(default=0, verbose_name='Kontrakt miqdori')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AllocatedAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('money', models.BigIntegerField()),
                ('sponsor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sponsor')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='student',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.university', verbose_name='OTM'),
        ),
    ]
