# Generated by Django 5.1.6 on 2025-02-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='payment_method',
            field=models.CharField(choices=[('transfer', 'Pul o‘tkazmalari'), ('cash', 'Naqd pul'), ('card', 'Plastik karta')], default='card', max_length=32, verbose_name='To‘lov turi'),
        ),
    ]
